logging.level:
  liquibase: INFO
  org.apache.kafka: WARN
  org.springframework.cloud.client.loadbalancer: INFO
  org.springframework.cloud.stream: INFO
  org.springframework.cloud.function: INFO
  org.springframework.r2dbc: DEBUG
  org.springframework.integration: INFO
  org.springframework.web: DEBUG
  com.vmware.labs.marketservice: DEBUG

server:
  port: ${PORT:9081}

spring:

  application:
    name: market-service

  datasource:
    driver-class-name: org.postgresql.Driver

  jackson:
    serialization:
      write-dates-as-timestamps: false

  cloud:

    kubernetes:

      config:
        enabled: false

      discovery:
        enabled: false

      enabled: false

    stream:

      function:
        definition: marketStatus

      bindings:
        marketStatus-out-0:
          destination: stocks.market-status

  liquibase:
    url: jdbc:postgresql://localhost:5432/market-status
    user: dfrey
    password:

  r2dbc:
    url: r2dbc:postgres://localhost:5432/market-status #?sslMode=disable
    username: dfrey
    password:
    properties:
      driver: postgresql
#      sslMode: DISABLE

  sleuth:
    enabled: false
    traceId128: true
    sampler.probability: 1.0
    web.skipPattern: (^cleanup.*|.+favicon.*)

  sql:
    init:
      mode: never

#Actuator
management:
  endpoints:
    web.exposure.include: '*'
  endpoint:
    health:
      show-details: ALWAYS
    restart:
      enabled: true

market-service:
#  open-cron: "0 */1 * * * *"
#  close-cron: "0 */1 * * * *"
  open-cron: "0 0 9 * * MON-FRI"
  close-cron: "0 30 4 * * MON-FRI"
  # cron format: second, minute, hour, day of month, month, day(s) of week


---
spring:

  config:
    activate:
      on-profile: localk8s

  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: user
    password: Qdd1PxtBRV

---
spring:

  config:
    activate:
      on-profile: cloud
      on-cloud-platform: kubernetes

  cloud:

    kubernetes:
      config:
        enabled: true
        name: market-service
        namespace: spring-stocks

      discovery:
        enabled: true

      enabled: true

  sleuth:
    enabled: true

market-service:
  open-cron: "0 0 9 * * MON-FRI"
  close-cron: "0 30 4 * * MON-FRI"
