logging.level:
  org.springframework.amqp: INFO
  org.springframework.cloud.client.loadbalancer: INFO
  org.springframework.cloud.stream: DEBUG
  org.springframework.cloud.function: DEBUG
  org.springframework.data.jpa: INFO
  org.springframework.jdbc: INFO
  org.springframework.integration: DEBUG
  org.springframework.web: DEBUG
  com.vmware.labs.marketService: DEBUG

server:
  port: ${PORT:9081}

spring:

  application:
    name: market-service

  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=MYSQL

  jackson:
    serialization:
      write-dates-as-timestamps: false

  jpa:
    hibernate:
      ddl-auto: validate

  cloud:

    kubernetes:

      config:
        enabled: false

      discovery:
        enabled: false

      enabled: false

    stream:

      function:
        definition: marketStatus

      bindings:
        marketStatus-out-0:
          destination: stocks.market-status

  sleuth:
    enabled: false
    traceId128: true
    sampler.probability: 1.0
    web.skipPattern: (^cleanup.*|.+favicon.*)

  sql:
    init:
      mode: never

#Actuator
management:
  endpoints:
    web.exposure.include: '*'
  endpoint:
    health:
      show-details: ALWAYS
    restart:
      enabled: true


---
spring:

  config:
    activate:
      on-profile: localk8s

  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: user
    password: Qdd1PxtBRV

---
spring:

  config:
    activate:
      on-profile: kubernetes

  cloud:

    kubernetes:
      config:
        enabled: true
        name: market-service
        namespace: spring-stocks

      discovery:
        enabled: true

      enabled: true

  sleuth:
    enabled: true
