logging.level:
  org.springframework.amqp: INFO
  org.springframework.cloud.client.loadbalancer: INFO
  org.springframework.cloud.stream: DEBUG
  org.springframework.cloud.function: DEBUG
  org.springframework.data.jpa: INFO
  org.springframework.jdbc: INFO
  org.springframework.integration: DEBUG
  org.springframework.web: DEBUG
  com.vmware.labs.marketService: DEBUG

server:
  port: ${PORT:9081}

spring:

  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=MYSQL
    initialization-mode: never

  jackson:
    serialization:
      write-dates-as-timestamps: false

  jpa:
    hibernate:
      ddl-auto: validate

  cloud:

    stream:

      function:
        definition: marketStatus

      bindings:
        marketStatus-out-0:
          destination: stocks.market-status

  sleuth:
    traceId128: true
    sampler.probability: 1.0
    web.skipPattern: (^cleanup.*|.+favicon.*)

#Actuator
management:
  endpoints:
    web.exposure.include: '*'
  endpoint:
    health:
      show-details: ALWAYS
    restart:
      enabled: true


---
spring:

  config:
    activate:
      on-profile: localk8s

  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: user
    password: Qdd1PxtBRV

