logging.level:
  org.springframework.amqp: DEBUG
  org.springframework.cloud.stream: DEBUG
  org.springframework.cloud.function: DEBUG
  org.springframework.web: DEBUG
  com.vmware.labs.stockService: DEBUG
  com.wavefront: DEBUG

server:
  port: ${PORT:9081}

spring:

  jackson:
    serialization:
      write-dates-as-timestamps: false

  sleuth:
    traceId128: true
    sampler.probability: 1.0
    web.skipPattern: (^cleanup.*|.+favicon.*)

#Actuator
management:
  endpoints:
    web.exposure.include: health,info,env,beans,integrationgraph,loggers,metrics,mappings,scheduledtasks,wavefront
  endpoint:
    health:
      show-details: ALWAYS
    restart:
      enabled: true

# Wavefront Observability
wavefront:
  application:
    name: spring-stocks
    service: market-service


---
spring:
  profiles: localk8s

  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: user
    password: Qdd1PxtBRV

