apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: spring-stocks
  annotations:
    github.com/project-slug: ddn4/spring-stocks
    backstage.io/techdocs-ref: dir:.
  tags:
    - parent
spec:
  type: other
  lifecycle: experimental
  owner: dmfrey
  catalog:
    locations:
      - type: url
        target: https://github.com/ddn4/spring-stocks/blob/master/market-service/catalog-info.yaml

