apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: spring-stocks
  title: Spring Stocks Parent
  description: Parent project of Spring Stocks applications
  annotations:
    github.com/project-slug: ddn4/spring-stocks
    backstage.io/techdocs-ref: dir:.
  tags:
    - parent
spec:
  lifecycle: experimental
  owner: dmfrey
#---
#apiVersion: backstage.io/v1alpha1
#kind: Location
#metadata:
#  name: spring-stocks-projects
#spec:
#  targets:
#    - ./market-service/catalog-info.yml

