server:
  http_listen_port: 7090
  grpc_listen_port: 0

positions:
  filename: logs/positions.yaml # This location needs to be writeable by Promtail.

client:
  url: http://localhost:3100/loki/api/v1/push

scrape_configs:
- job_name: market-service
  pipeline_stages:
#    - json:
#        expressions:
#          level: level
#          message: message
#          timestamp: '"@timestamp"'
#          logger_name: logger_name
#          stack_trace: stack_trace
#          thread_name: thread_name
#          traceId: traceId
#          spanId: spanId
#    - labels:
#        level:
#        traceId: traceId
#        spanId: spanId
#    - template:
#        source: new_key
#        template: 'logger={{ .logger_name }} threadName={{ .thread_name }} | {{ or .message .stack_trace }}'
#    - output:
#        source: new_key
  static_configs:
    - targets:
        - localhost
      labels:
        job: market-service  # A `job` label is fairly standard in prometheus and useful for linking metrics and logs.
        __path__: logs/market-service.log  # The path matching uses a third party library: https://github.com/bmatcuk/doublestar
- job_name: stock-service
  pipeline_stages:
#    - json:
#        expressions:
#          level: level
#          message: message
#          timestamp: '"@timestamp"'
#          logger_name: logger_name
#          stack_trace: stack_trace
#          thread_name: thread_name
#          traceId: traceId
#          spanId: spanId
#    - labels:
#        level:
#        traceId:
#        spanId:
#    - template:
#        source: new_key
#        template: 'logger={{ .logger_name }} threadName={{ .thread_name }} | {{ or .message .stack_trace }}'
#    - output:
#        source: new_key
  static_configs:
    - targets:
        - localhost
      labels:
        job: stock-service  # A `job` label is fairly standard in prometheus and useful for linking metrics and logs.
        __path__: logs/stock-service.log  # The path matching uses a third party library: https://github.com/bmatcuk/doublestar
- job_name: gateway
  pipeline_stages:
#    - json:
#        expressions:
#          level: level
#          message: message
#          timestamp: '"@timestamp"'
#          logger_name: logger_name
#          stack_trace: stack_trace
#          thread_name: thread_name
#          traceId: traceId
#          spanId: spanId
#    - labels:
#        level:
#        traceId: traceId
#        spanId: spanId
#    - template:
#        source: new_key
#        template: 'logger={{ .logger_name }} threadName={{ .thread_name }} | {{ or .message .stack_trace }}'
#    - output:
#        source: new_key
  static_configs:
    - targets:
        - localhost
      labels:
        job: gateway  # A `job` label is fairly standard in prometheus and useful for linking metrics and logs.
        __path__: logs/gateway.log  # The path matching uses a third party library: https://github.com/bmatcuk/doublestar
