
logging.level:
  org.springframework.amqp: DEBUG
  org.springframework.cloud.stream: DEBUG
  org.springframework.cloud.function: DEBUG
  org.springframework.web: DEBUG
  com.vmware.labs.stockService: DEBUG
  com.wavefront: DEBUG

server:
  port: ${PORT:9080}

spring:

  jackson:
    serialization:
      write-dates-as-timestamps: false

  cloud:
    stream:

      function:
        definition: stockUpdateListener;marketStatusListener

      bindings:
        stockUpdateListener-in-0:
          destination: stocks.symbol-update
          group: stock-service
        marketStatusListener-in-0:
          destination: stocks.market-status
          group: stock-service

  sleuth:
    traceId128: true
    sampler.probability: 1.0
    web.skipPattern: (^cleanup.*|.+favicon.*)

  stocks:
    seeder:
      enabled: true

#Actuator
management:
  endpoints:
    web.exposure.include: health,info,env,beans,integrationgraph,loggers,metrics,mappings,scheduledtasks,wavefront
  endpoint:
    health:
      show-details: ALWAYS
    restart:
      enabled: true
  metrics:
    export:
      wavefront:
        api-token: 98441cb6-c78b-49f3-a716-6ef65b6bbe04
        uri: https://wavefront.surf

# Wavefront Observability
wavefront:
  application:
    name: spring-stocks
    service: stock-service


---
spring:
  profiles: localk8s

  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: user
    password: Qdd1PxtBRV

