
logging.level:
  org.springframework.cloud.client.loadbalancer: DEBUG
  org.springframework.cloud.stream: INFO
  org.springframework.cloud.function: INFO
  org.springframework.web: DEBUG
  com.vmware.labs.stockservice: DEBUG

server:
  port: ${PORT:9080}

spring:

  application:
    name: stock-service

  jackson:
    serialization:
      write-dates-as-timestamps: false

  cloud:

    kubernetes:

      config:
        enabled: false

      discovery:
        enabled: false

    stream:

      function:
        definition: stockUpdateListener;marketStatusListener

      bindings:
        stockUpdateListener-in-0:
          destination: stocks.symbol-update
          group: stock-service
        marketStatusListener-in-0:
          destination: stocks.market-status
          group: stock-service

  sleuth:
    enabled: false
    traceId128: true
    sampler.probability: 1.0
    web.skipPattern: (^cleanup.*|.+favicon.*)

  stocks:
    seeder:
      enabled: true

#Actuator
management:
  endpoints:
    web.exposure.include: '*'
  endpoint:
    health:
      show-details: ALWAYS
    restart:
      enabled: true


---
spring:

  config:
    activate:
      on-profile: localk8s

  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: user
    password: Qdd1PxtBRV

---
spring:

  config:
    activate:
      on-profile: kubernetes

  cloud:

    kubernetes:

      config:
        name: stock-service
        namespace: spring-stocks

      discovery:
        enabled: true

  sleuth:
    enabled: true
