
logging.level:
  org.springframework.amqp: DEBUG
  org.springframework.cloud.stream: DEBUG
  org.springframework.cloud.function: DEBUG
  org.springframework.web: DEBUG
  com.vmware.labs.stockService: DEBUG

server:
  port: ${PORT:9080}

spring:

  jackson:
    serialization:
      write-dates-as-timestamps: false

    stream:
      bindings:
        stockUpdateListener-in-0:
          destination: stocks.update
          group: spring-stocks

  stocks:
    seeder:
      enabled: true

#Actuator
management:
  endpoints:
    web.exposure.include: "*"
  endpoint:
    health:
      show-details: ALWAYS
    restart:
      enabled: true

---
spring:
  profiles: localk8s

  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: user
    password: Qdd1PxtBRV

