---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rabbitmq
  namespace: spring-stocks
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: rabbitmq-peer-discovery-rbac
  namespace: spring-stocks
rules:
- apiGroups: [""]
  resources: ["endpoints"]
  verbs: ["get"]
# - apiGroups: [""]
#   resources: ["events"]
#   verbs: ["create"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: rabbitmq-peer-discovery-rbac
  namespace: spring-stocks
subjects:
- kind: ServiceAccount
  name: rabbitmq
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: rabbitmq-peer-discovery-rbac

