
logging:
  level:
    liquibase: INFO
    org.apache.kafka: WARN
    org.springframework.cloud.client.loadbalancer: INFO
    org.springframework.cloud.stream: INFO
    org.springframework.cloud.sleuth: INFO
    org.springframework.cloud.sleuth.instrument.r2dbc: INFO
    org.springframework.cloud.function: INFO
    org.springframework.r2dbc: INFO
    org.springframework.integration: INFO
    org.springframework.web: INFO
    com.vmware.labs.stockservice: DEBUG
  file:
    name: logs/${spring.application.name}.log
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 1
  pattern:
    file: "date=%d{yyyy-MM-dd} time=%d{HH:mm:ss.SSS} thread=%thread level=%-5level logger=%logger{36} service=${spring.application.name} traceId=%X{traceId} spanId=%X{spanId} - message=%msg%n"

server:
  port: ${PORT:7080}

spring:

  application:
    name: stock-service

  datasource:
    driver-class-name: org.postgresql.Driver

  jackson:
    serialization:
      write-dates-as-timestamps: false

  cloud:

    stream:

      function:
        definition: stockUpdateListener;marketStatusListener

      bindings:
        stockUpdateListener-in-0:
          destination: stocks.symbol-update
          group: stock-service
        marketStatusListener-in-0:
          destination: stocks.market-status
          group: stock-service

  liquibase:
    url: jdbc:postgresql://localhost:5432/stock-service
    user: dfrey
    password:

  r2dbc:
    url: r2dbc:postgres://localhost:5432/stock-service
    username: dfrey
    password:
    properties:
      driver: postgresql

  sleuth:
    traceId128: true
    sampler.probability: 1.0
    web.skipPattern: (^cleanup.*|.+favicon.*)
    r2dbc.enabled: true

  zipkin:
    baseUrl: http://localhost:9411/

  sql:
    init:
      mode: never

  stocks:
    seeder:
      enabled: true

#Actuator
management:
  endpoints:
    web.exposure.include: '*'
  endpoint:
    health:
      show-details: ALWAYS
    restart:
      enabled: true


---
spring:

  config:
    activate:
      on-profile: localk8s

  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: user
    password: Qdd1PxtBRV

---
spring:

  config:
    activate:
      on-profile: kubernetes

  sleuth:
    enabled: true
