apiVersion: apps/v1
kind: Deployment
metadata:
  name: market-service-deployment
  namespace: spring-stocks
  labels:
    app: market-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: market-service
  template:
    metadata:
      labels:
        app: market-service
    spec:
      containers:
        - name: market-service
          image: dmfrey/market-service
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_RABBITMQ_HOST
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: host
            - name: SPRING_RABBITMQ_PORT
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: port
            - name: SPRING_RABBITMQ_USERNAME
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: username
            - name: SPRING_RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: password
