---
apiVersion: v1
kind: Service
metadata:
  name: market-service
  namespace: spring-stocks
spec:
  selector:
    app: market-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: market-service-deployment
  namespace: spring-stocks
  labels:
    app: market-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: market-service
  template:
    metadata:
      labels:
        app: market-service
    spec:
      serviceAccountName: spring-stocks
      containers:
        - name: market-service
          image: dmfrey/market-service
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 120
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 120
            periodSeconds: 5
          volumeMounts:
            - name: wavefront-freemium
              mountPath: ./wavefront_freemium
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                secretKeyRef:
                  name: market-service-mysql-secret
                  key: uri
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: market-service-mysql-secret
                  key: database
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: market-service-mysql-secret
                  key: password
            - name: SPRING_RABBITMQ_SSL_ENABLED
              value: "false"
            - name: SPRING_RABBITMQ_HOST
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: host
            - name: SPRING_RABBITMQ_PORT
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: port
            - name: SPRING_RABBITMQ_USERNAME
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: username
            - name: SPRING_RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: password
#            - name: MANAGEMENT_METRICS_EXPORT_WAVEFRONT_APITOKEN
#              valueFrom:
#                secretKeyRef:
#                  name: wavefront-secret
#                  key: api-token
#            - name: MANAGEMENT_METRICS_EXPORT_WAVEFRONT_URI
#              valueFrom:
#                secretKeyRef:
#                  name: wavefront-secret
#                  key: uri
      volumes:
        - name: wavefront-freemium
          secret:
            secretName: wavefront-secret
            items:
            - key: api-token
              path: api-token
