apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: spring-stocks-role
  namespace: spring-stocks
rules:
  - apiGroups: ["", "extensions", "apps"]
    resources: ["configmaps", "pods", "services", "endpoints", "secrets"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: spring-stocks-role-binding
  namespace: spring-stocks
subjects:
  - kind: ServiceAccount
    name: default
    apiGroup: ""
roleRef:
  kind: Role
  name: spring-stocks-role
  apiGroup: ""
