---
apiVersion: v1
kind: Service
metadata:
  name: stock-service
  namespace: spring-stocks
spec:
  selector:
    app: stock-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stock-service-deployment
  namespace: spring-stocks
  labels:
    app: stock-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stock-service
  template:
    metadata:
      labels:
        app: stock-service
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: /actuator/prometheus
    spec:
      serviceAccountName: default
      containers:
        - name: stock-service
          image: stock-service
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 180
            periodSeconds: 60
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 180
            periodSeconds: 60
          env:
            - name: ORG_SPRINGFRAMEWORK_CLOUD_BINDINGS_BOOT_ENABLE
              value: "true"
            - name: SPRING_RABBITMQ_SSL_ENABLED
              value: "false"
            - name: SPRING_RABBITMQ_VIRTUAL_HOST
              value: "/"
            - name: SPRING_RABBITMQ_HOST
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: host
            - name: SPRING_RABBITMQ_PORT
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: port
            - name: SPRING_RABBITMQ_USERNAME
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: username
            - name: SPRING_RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: password
#            - name: SPRING_LIQUIBASE_URL
#              valueFrom:
#                secretKeyRef:
#                  name: postgres-secret
#                  key: url
#            - name: SPRING_LIQUIBASE_USER
#              valueFrom:
#                secretKeyRef:
#                  name: postgres-secret
#                  key: username
#            - name: SPRING_LIQUIBASE_PASSWORD
#              valueFrom:
#                secretKeyRef:
#                  name: postgres-secret
#                  key: password
#            - name: SPRING_R2DBC_URL
#              valueFrom:
#                secretKeyRef:
#                  name: postgres-secret
#                  key: url
#            - name: SPRING_R2DBC_USER
#              valueFrom:
#                secretKeyRef:
#                  name: postgres-secret
#                  key: username
#            - name: SPRING_R2DBC_PASSWORD
#              valueFrom:
#                secretKeyRef:
#                  name: postgres-secret
#                  key: password
