kind: ConfigMap
apiVersion: v1
metadata:
  name: stock-service
  namespace: spring-stocks
data:
  application.yaml: |-
    spring:

      stocks:
        seeder:
          enabled: false

    server:
      port: 8080