
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web: DEBUG
    com.vmware.labs.springstockgateway: DEBUG
  file:
    name: logs/${spring.application.name}.log
  logback:
    rollingpolicy:
      max-file-size: 5MB
      max-history: 1
      clean-history-on-start: true
  pattern:
    file: "date=%d{yyyy-MM-dd} time=%d{HH:mm:ss.SSS} thread=%thread level=%-5level logger=%logger{36} service=${spring.application.name} traceId=%X{traceId} spanId=%X{spanId} - message=%msg%n"

server:
  port: ${PORT:8765}

spring:

  application:
    name: spring-stocks-gateway

  cloud:

    kubernetes:

      config:
        enabled: false

      discovery:
        enabled: false

  sleuth:
    enabled: false
    traceId128: true
    sampler.probability: 1.0
    web.skipPattern: (^cleanup.*|.+favicon.*)

#Actuator
management:
  endpoints:
    web.exposure.include: '*'
  endpoint:
    health:
      show-details: ALWAYS
    restart:
      enabled: true


---
spring:

  config:
    activate:
      on-profile: kubernetes

  cloud:

    gateway:

      discovery.locator.enabled: false
      
      default-filters:
        - StripPrefix=2
        - RemoveResponseHeader=Set-Cookie

      routes:
      - id: stock-service
        uri: http://stock-service
        predicates:
          - Path=/api/stock-service/**
        # filters:
        #   - name: CircuitBreaker
        #     args:
        #       name: errorCircuitBreaker
        #       fallbackUri: forward:/error.html
      - id: market-service
        uri: http://market-service
        predicates:
          - Path=/api/market-service/**
        # filters:
        #   - name: CircuitBreaker
        #     args:
        #       name: errorCircuitBreaker
        #       fallbackUri: forward:/error.html

  sleuth:
    enabled: true

