
logging.level:
  org.springframework.cloud.stream: DEBUG
  org.springframework.web: DEBUG
  com.vmware.labs.task.marketStatus: DEBUG

server:
  port: ${PORT:9082}

spring:

  application:
    name: market-status

  jackson:
    serialization:
      write-dates-as-timestamps: false

  cloud:

    function:
      definition: dateToMarketStatusConverter

    stream:
      function:
        bindings:
          dateToMarketStatusConverter-in-0: input
          dateToMarketStatusConverter-out-0: output

    kubernetes:

      discovery:
        enabled: false

      config:
        enabled: false

#Actuator
management:
  endpoints:
    web.exposure.include: '*'
  endpoint:
    health:
      show-details: ALWAYS

---
spring:
  config:
    activate:
      on-profile: kubernetes

  cloud:

    kubernetes:
      config:
        enabled: true
        name: market-status
        namespace: spring-stocks
